image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - Ionide.Ionide-fsharp@5.0.0-preview02:onZnF31wzCmbSixApgEq2Q==
    - ms-dotnettools.csharp@1.23.6:qOOlFzbLQsGAgQYbPRugSw==
tasks:
  - init: dotnet tool restore
ports:
  - port: 8080
    onOpen: open-browser